# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3835bbb3270651b1a86ba603b4dd28cc1c972a861281ab5ef73aa0818feb996576725cd7c4e20363eaab373591be26ab467a89cfb8471ee3082f25b4cbf2a6a

test:
  secret_key_base: d938da6c44e65fe6ebd9c800acd0d8d55efb3df841794c4d3830764bebec3b1922a024bca4ce70ae8252f2926ca0ad1238373eee4222224027a490d09c746259

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
